using System.Net;
using System.Net.Mail;
using System.Text;

namespace Backup.Server.Services;

public interface INotificationService
{
    Task SendAsync(string recipient, string subject, string body);
    Task SendBatchAsync(List<string> recipients, string subject, string body);
}

public class EmailNotificationService : INotificationService
{
    private readonly ILogger<EmailNotificationService> _logger;
    private readonly SmtpClient _smtpClient;
    private readonly string _fromAddress;
    private readonly string _fromName;

    public EmailNotificationService(ILogger<EmailNotificationService> logger, IConfiguration config)
    {
        _logger = logger;
        
        var smtpHost = config["Smtp:Host"] ?? "localhost";
        var smtpPort = int.Parse(config["Smtp:Port"] ?? "25");
        var username = config["Smtp:Username"];
        var password = config["Smtp:Password"];
        _fromAddress = config["Smtp:FromAddress"] ?? "noreply@backupsystem.com";
        _fromName = config["Smtp:FromName"] ?? "Backup System";

        _smtpClient = new SmtpClient(smtpHost, smtpPort)
        {
            EnableSsl = bool.Parse(config["Smtp:EnableSsl"] ?? "false"),
            Credentials = string.IsNullOrEmpty(username) 
                ? null 
                : new NetworkCredential(username, password)
        };
    }

    public async Task SendAsync(string recipient, string subject, string body)
    {
        try
        {
            var message = new MailMessage
            {
                From = new MailAddress(_fromAddress, _fromName),
                Subject = subject,
                Body = body,
                IsBodyHtml = true,
                Priority = MailPriority.Normal
            };
            message.To.Add(recipient);

            await _smtpClient.SendMailAsync(message);
            _logger.LogInformation("Email sent to {Recipient}", recipient);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to send email to {Recipient}", recipient);
        }
    }

    public async Task SendBatchAsync(List<string> recipients, string subject, string body)
    {
        foreach (var recipient in recipients)
        {
            await SendAsync(recipient, subject, body);
        }
    }
}

public class NotificationTemplates
{
    public static string JobCompleted(string jobName, string duration, string size)
    {
        return $@"
            <html>
            <body style='font-family: Arial, sans-serif;'>
                <h2>Backup Job Completed</h2>
                <p>The backup job <strong>{jobName}</strong> has completed successfully.</p>
                <table style='border-collapse: collapse;'>
                    <tr><td style='padding: 8px; border: 1px solid #ddd;'><strong>Duration:</strong></td><td style='padding: 8px; border: 1px solid #ddd;'>{duration}</td></tr>
                    <tr><td style='padding: 8px; border: 1px solid #ddd;'><strong>Size:</strong></td><td style='padding: 8px; border: 1px solid #ddd;'>{size}</td></tr>
                </table>
                <p style='color: #666; font-size: 12px;'>Generated by Backup System</p>
            </body>
            </html>";
    }

    public static string JobFailed(string jobName, string error)
    {
        return $@"
            <html>
            <body style='font-family: Arial, sans-serif;'>
                <h2 style='color: #d32f2f;'>Backup Job Failed</h2>
                <p>The backup job <strong>{jobName}</strong> has failed.</p>
                <div style='background: #ffebee; padding: 16px; border-radius: 4px;'>
                    <strong>Error:</strong> {error}
                </div>
                <p style='color: #666; font-size: 12px;'>Generated by Backup System</p>
            </body>
            </html>";
    }

    public static string RestoreCompleted(string restoreId, string vmName)
    {
        return $@"
            <html>
            <body style='font-family: Arial, sans-serif;'>
                <h2>Restore Completed</h2>
                <p>Restore <strong>{restoreId}</strong> for VM <strong>{vmName}</strong> has completed successfully.</p>
                <p style='color: #666; font-size: 12px;'>Generated by Backup System</p>
            </body>
            </html>";
    }

    public static string StorageAlert(string repositoryName, string usagePercent)
    {
        return $@"
            <html>
            <body style='font-family: Arial, sans-serif;'>
                <h2 style='color: #ed6c02;'>Storage Alert</h2>
                <p>Repository <strong>{repositoryName}</strong> is at <strong>{usagePercent}%</strong> capacity.</p>
                <p>Please consider adding more storage or cleaning up old backups.</p>
                <p style='color: #666; font-size: 12px;'>Generated by Backup System</p>
            </body>
            </html>";
    }

    public static string DailyReport(string totalBackups, string successRate, string totalSize)
    {
        return $@"
            <html>
            <body style='font-family: Arial, sans-serif;'>
                <h2>Daily Backup Report</h2>
                <table style='border-collapse: collapse;'>
                    <tr><td style='padding: 8px; border: 1px solid #ddd;'><strong>Total Backups:</strong></td><td style='padding: 8px; border: 1px solid #ddd;'>{totalBackups}</td></tr>
                    <tr><td style='padding: 8px; border: 1px solid #ddd;'><strong>Success Rate:</strong></td><td style='padding: 8px; border: 1px solid #ddd;'>{successRate}</td></tr>
                    <tr><td style='padding: 8px; border: 1px solid #ddd;'><strong>Total Size:</strong></td><td style='padding: 8px; border: 1px solid #ddd;'>{totalSize}</td></tr>
                </table>
                <p style='color: #666; font-size: 12px;'>Generated by Backup System</p>
            </body>
            </html>";
    }
}
