using System.Text;
using System.Text.Json;

namespace Backup.Server.Services;

public class PdfReportService
{
    private readonly ILogger<PdfReportService> _logger;
    private readonly BackupDbContext _db;

    public PdfReportService(ILogger<PdfReportService> logger, BackupDbContext db)
    {
        _logger = logger;
        _db = db;
    }

    public async Task<byte[]> GenerateDailyReportAsync(DateTime date)
    {
        var html = await GenerateDailyReportHtmlAsync(date);
        return await ConvertHtmlToPdfAsync(html);
    }

    public async Task<byte[]> GenerateWeeklyReportAsync(DateTime weekStart)
    {
        var html = await GenerateWeeklyReportHtmlAsync(weekStart);
        return await ConvertHtmlToPdfAsync(html);
    }

    public async Task<byte[]> GenerateMonthlyReportAsync(int year, int month)
    {
        var html = await GenerateMonthlyReportHtmlAsync(year, month);
        return await ConvertHtmlToPdfAsync(html);
    }

    public async Task<byte[]> GenerateCustomReportAsync(ReportRequest request)
    {
        var html = await GenerateCustomReportHtmlAsync(request);
        return await ConvertHtmlToPdfAsync(html);
    }

    private async Task<string> GenerateDailyReportHtmlAsync(DateTime date)
    {
        var startDate = date.Date;
        var endDate = startDate.AddDays(1);

        var jobs = await _db.JobRunHistory
            .Where(h => h.StartTime >= startDate && h.StartTime < endDate)
            .ToListAsync();

        var backups = await _db.BackupPoints
            .Where(b => b.CreatedAt >= startDate && b.CreatedAt < endDate)
            .ToListAsync();

        var sb = new StringBuilder();
        sb.Append($@"
<!DOCTYPE html>
<html>
<head>
    <title>Daily Backup Report - {date:yyyy-MM-dd}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        h1 {{ color: #1976d2; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
        th {{ background: #1976d2; color: white; }}
        .success {{ color: #2e7d32; }}
        .failed {{ color: #d32f2f; }}
        .summary {{ background: #f5f5f5; padding: 20px; border-radius: 8px; }}
    </style>
</head>
<body>
    <h1>Daily Backup Report</h1>
    <p>Date: {date:yyyy-MM-dd}</p>
    
    <div class='summary'>
        <h2>Summary</h2>
        <p>Total Jobs: <strong>{jobs.Count}</strong></p>
        <p>Completed: <strong class='success'>{jobs.Count(j => j.Status == "completed")}</strong></p>
        <p>Failed: <strong class='failed'>{jobs.Count(j => j.Status == "failed")}</strong></p>
        <p>Total Backups: <strong>{backups.Count}</strong></p>
    </div>
    
    <h2>Job Details</h2>
    <table>
        <tr>
            <th>Job ID</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Status</th>
            <th>Size (MB)</th>
            <th>Duration</th>
        </tr>");

        foreach (var job in jobs)
        {
            var duration = job.EndTime.HasValue 
                ? (job.EndTime.Value - job.StartTime).ToString(@"hh\:mm\:ss") 
                : "-";
            var size = (job.BytesProcessed / 1024.0 / 1024.0).ToString("F2");
            var statusClass = job.Status == "completed" ? "success" : "failed";
            
            sb.Append($@"
        <tr>
            <td>{job.JobId}</td>
            <td>{job.StartTime:HH:mm:ss}</td>
            <td>{job.EndTime?.ToString("HH:mm:ss") ?? "-"}</td>
            <td class='{statusClass}'>{job.Status}</td>
            <td>{size}</td>
            <td>{duration}</td>
        </tr>");
        }

        sb.Append(@"
    </table>
    <p style='color: #666; margin-top: 40px;'>Generated by Backup System</p>
</body>
</html>");

        return sb.ToString();
    }

    private async Task<string> GenerateWeeklyReportHtmlAsync(DateTime weekStart)
    {
        var endDate = weekStart.AddDays(7);

        var jobs = await _db.JobRunHistory
            .Where(h => h.StartTime >= weekStart && h.StartTime < endDate)
            .ToListAsync();

        var backups = await _db.BackupPoints
            .Where(b => b.CreatedAt >= weekStart && b.CreatedAt < endDate)
            .ToListAsync();

        var totalSize = backups.Sum(b => b.SizeBytes);
        var successRate = jobs.Count > 0 
            ? (double)jobs.Count(j => j.Status == "completed") / jobs.Count * 100 
            : 0;

        var sb = new StringBuilder();
        sb.Append($@"
<!DOCTYPE html>
<html>
<head>
    <title>Weekly Backup Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        h1 {{ color: #1976d2; }}
        .summary {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin: 20px 0; }}
        .card {{ background: #f5f5f5; padding: 20px; border-radius: 8px; text-align: center; }}
        .card h3 {{ margin: 0; font-size: 32px; }}
        .card p {{ color: #666; margin: 0; }}
    </style>
</head>
<body>
    <h1>Weekly Backup Report</h1>
    <p>Period: {weekStart:yyyy-MM-dd} - {endDate.AddDays(-1):yyyy-MM-dd}</p>
    
    <div class='summary'>
        <div class='card'>
            <h3>{jobs.Count}</h3>
            <p>Total Jobs</p>
        </div>
        <div class='card'>
            <h3>{backups.Count}</h3>
            <p>Total Backups</p>
        </div>
        <div class='card'>
            <h3>{(totalSize / 1024.0 / 1024.0 / 1024.0).ToString("F2")} GB</h3>
            <p>Total Size</p>
        </div>
        <div class='card'>
            <h3>{successRate:F1}%</h3>
            <p>Success Rate</p>
        </div>
    </div>
    
    <p style='color: #666;'>Generated by Backup System</p>
</body>
</html>");

        return sb.ToString();
    }

    private async Task<string> GenerateMonthlyReportHtmlAsync(int year, int month)
    {
        var startDate = new DateTime(year, month, 1);
        var endDate = startDate.AddMonths(1);

        var jobs = await _db.JobRunHistory
            .Where(h => h.StartTime >= startDate && h.StartTime < endDate)
            .ToListAsync();

        var backups = await _db.BackupPoints
            .Where(b => b.CreatedAt >= startDate && b.CreatedAt < endDate)
            .ToListAsync();

        var totalSize = backups.Sum(b => b.SizeBytes);
        var successRate = jobs.Count > 0 
            ? (double)jobs.Count(j => j.Status == "completed") / jobs.Count * 100 
            : 0;

        return $@"
<!DOCTYPE html>
<html>
<head>
    <title>Monthly Report - {year}-{month:D2}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        h1 {{ color: #1976d2; }}
    </style>
</head>
<body>
    <h1>Monthly Report - {year} {month:D2}</h1>
    <p>Total Jobs: {jobs.Count}</p>
    <p>Total Backups: {backups.Count}</p>
    <p>Total Size: {(totalSize / 1024.0 / 1024.0 / 1024.0).ToString("F2")} GB</p>
    <p>Success Rate: {successRate:F1}%</p>
</body>
</html>";
    }

    private async Task<string> GenerateCustomReportHtmlAsync(ReportRequest request)
    {
        var jobs = await _db.JobRunHistory
            .Where(h => request.JobIds.Contains(h.JobId))
            .ToListAsync();

        return $@"
<!DOCTYPE html>
<html>
<head>
    <title>Custom Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
    </style>
</head>
<body>
    <h1>Custom Report</h1>
    <p>Jobs: {string.Join(", ", request.JobIds)}</p>
    <p>Total: {jobs.Count} records</p>
</body>
</html>";
    }

    private async Task<byte[]> ConvertHtmlToPdfAsync(string html)
    {
        await Task.Delay(100);
        
        return Encoding.UTF8.GetBytes(html);
    }
}

public class ReportRequest
{
    public List<string> JobIds { get; set; } = new();
    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }
    public ReportType Type { get; set; }
}

public enum ReportType
{
    Daily,
    Weekly,
    Monthly,
    Custom
}
